version: '3'
services:
  app:
    container_name: blagues_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./blagues.json:/app/blagues.json
    env_file:
      - ./.env
    ports:
      - '4000:4000'
    networks:
      - global

  postgres:
    container_name: blagues_api_postgres
    image: 'postgres:13'
    volumes:
      - ./databases/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - '5440:5432'
    networks:
      - global

networks:
  global:
