version: '3'
services:
  app:
    container_name: blagues-api
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '3000:3000'
