version: '3'
services:
  app:
    container_name: blagues-api
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./blagues.json:/app/blagues.json
      - ./database.db:/app/database.db
      - ./prisma:/app/prisma
      - ./nuxt.config.js:/app/nuxt.config.js
    env_file:
      - ./.env
    ports:
      - '3000:3000'
